version: '3'

services:
  app:
    build: './src/app'
    volumes:
      - './src/app/html:/usr/share/nginx/html'
    ports:
      - '80:80'
    depends_on:
      - 'api'

  api:
    hostname: 'api'
    build: './src/api'
    volumes:
      - './src/api:/app'
    ports:
      - '8080:80'
